version: "3.4"

services:
  php:
    container_name: unsecure-php
    build: .docker/local/php
    depends_on:
      - db
    volumes:
      - .:/home/unsecure:rw

  web:
    container_name: unsecure-web
    image: nginx:1.15-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./public:/home/unsecure/public:ro
      - ./.docker/local/nginx:/etc/nginx/conf.d:ro

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unsecure

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
